### ISSUE TITLE
openhpc-login-0: Unable to start service slurmd

### ISSUE THREAD

**Issue by tbludau** [stackhpc/ansible-role-openhpc#13]
Hey, 

i've started a deployment as described in the README. But after deploying (set hostname, and add Repos before) i got an error while starting the slurm daemon on the openhpc-login-0 node. 
I got the same error while have other hostnames of openhpc-compute-*, but solved this by changing the name announced in the README file. 

fatal: [openhpc-login-0]: FAILED! => {"changed": false, "msg": "Unable to start service slurmd: Job for slurmd.service failed because the control process exited with error code. See \"systemctl status slurmd.service\" and \"journalctl -xe\" for details.\n"}

When starting i got this message:
slurmd[21031]: fatal: Unable to determine this slurmd's NodeName

And after some research i saw this hostname of the login note is not wrote down in the slurm.conf Template file. (Only compute nodes).

I thing this a configuration problem in the template file or?

Thomas

**Comment by brtknr** [comment]
Hi @tbludau, did you manage to get any further? I think we have reproduced the issue.

**Comment by JohnGarbutt** [comment]
I have attempted to put together a PR that may help you: https://github.com/stackhpc/ansible-role-openhpc/pull/14
